// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/user_service.proto

package identityconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	identity "github.com/unionai/terraform-provider-unionai/proto/identity"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "cloudidl.identity.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/cloudidl.identity.UserService/CreateUser"
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/cloudidl.identity.UserService/GetUser"
	// UserServiceDeleteUserProcedure is the fully-qualified name of the UserService's DeleteUser RPC.
	UserServiceDeleteUserProcedure = "/cloudidl.identity.UserService/DeleteUser"
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/cloudidl.identity.UserService/ListUsers"
	// UserServiceListUsersCountProcedure is the fully-qualified name of the UserService's
	// ListUsersCount RPC.
	UserServiceListUsersCountProcedure = "/cloudidl.identity.UserService/ListUsersCount"
	// UserServiceGetUserAndGroupsForOrgProcedure is the fully-qualified name of the UserService's
	// GetUserAndGroupsForOrg RPC.
	UserServiceGetUserAndGroupsForOrgProcedure = "/cloudidl.identity.UserService/GetUserAndGroupsForOrg"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	userServiceServiceDescriptor                      = identity.File_identity_user_service_proto.Services().ByName("UserService")
	userServiceCreateUserMethodDescriptor             = userServiceServiceDescriptor.Methods().ByName("CreateUser")
	userServiceGetUserMethodDescriptor                = userServiceServiceDescriptor.Methods().ByName("GetUser")
	userServiceDeleteUserMethodDescriptor             = userServiceServiceDescriptor.Methods().ByName("DeleteUser")
	userServiceListUsersMethodDescriptor              = userServiceServiceDescriptor.Methods().ByName("ListUsers")
	userServiceListUsersCountMethodDescriptor         = userServiceServiceDescriptor.Methods().ByName("ListUsersCount")
	userServiceGetUserAndGroupsForOrgMethodDescriptor = userServiceServiceDescriptor.Methods().ByName("GetUserAndGroupsForOrg")
)

// UserServiceClient is a client for the cloudidl.identity.UserService service.
type UserServiceClient interface {
	CreateUser(context.Context, *connect.Request[identity.CreateUserRequest]) (*connect.Response[identity.CreateUserResponse], error)
	GetUser(context.Context, *connect.Request[identity.GetUserRequest]) (*connect.Response[identity.GetUserResponse], error)
	DeleteUser(context.Context, *connect.Request[identity.DeleteUserRequest]) (*connect.Response[identity.DeleteUserResponse], error)
	ListUsers(context.Context, *connect.Request[identity.ListUsersRequest]) (*connect.Response[identity.ListUsersResponse], error)
	ListUsersCount(context.Context, *connect.Request[identity.ListUsersCountRequest]) (*connect.Response[identity.ListUsersCountResponse], error)
	GetUserAndGroupsForOrg(context.Context, *connect.Request[identity.GetUserAndGroupsForOrgRequest]) (*connect.Response[identity.GetUserAndGroupsForOrgResponse], error)
}

// NewUserServiceClient constructs a client for the cloudidl.identity.UserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userServiceClient{
		createUser: connect.NewClient[identity.CreateUserRequest, identity.CreateUserResponse](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			connect.WithSchema(userServiceCreateUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[identity.GetUserRequest, identity.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceGetUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[identity.DeleteUserRequest, identity.DeleteUserResponse](
			httpClient,
			baseURL+UserServiceDeleteUserProcedure,
			connect.WithSchema(userServiceDeleteUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[identity.ListUsersRequest, identity.ListUsersResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceListUsersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listUsersCount: connect.NewClient[identity.ListUsersCountRequest, identity.ListUsersCountResponse](
			httpClient,
			baseURL+UserServiceListUsersCountProcedure,
			connect.WithSchema(userServiceListUsersCountMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getUserAndGroupsForOrg: connect.NewClient[identity.GetUserAndGroupsForOrgRequest, identity.GetUserAndGroupsForOrgResponse](
			httpClient,
			baseURL+UserServiceGetUserAndGroupsForOrgProcedure,
			connect.WithSchema(userServiceGetUserAndGroupsForOrgMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	createUser             *connect.Client[identity.CreateUserRequest, identity.CreateUserResponse]
	getUser                *connect.Client[identity.GetUserRequest, identity.GetUserResponse]
	deleteUser             *connect.Client[identity.DeleteUserRequest, identity.DeleteUserResponse]
	listUsers              *connect.Client[identity.ListUsersRequest, identity.ListUsersResponse]
	listUsersCount         *connect.Client[identity.ListUsersCountRequest, identity.ListUsersCountResponse]
	getUserAndGroupsForOrg *connect.Client[identity.GetUserAndGroupsForOrgRequest, identity.GetUserAndGroupsForOrgResponse]
}

// CreateUser calls cloudidl.identity.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[identity.CreateUserRequest]) (*connect.Response[identity.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// GetUser calls cloudidl.identity.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[identity.GetUserRequest]) (*connect.Response[identity.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// DeleteUser calls cloudidl.identity.UserService.DeleteUser.
func (c *userServiceClient) DeleteUser(ctx context.Context, req *connect.Request[identity.DeleteUserRequest]) (*connect.Response[identity.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// ListUsers calls cloudidl.identity.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[identity.ListUsersRequest]) (*connect.Response[identity.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// ListUsersCount calls cloudidl.identity.UserService.ListUsersCount.
func (c *userServiceClient) ListUsersCount(ctx context.Context, req *connect.Request[identity.ListUsersCountRequest]) (*connect.Response[identity.ListUsersCountResponse], error) {
	return c.listUsersCount.CallUnary(ctx, req)
}

// GetUserAndGroupsForOrg calls cloudidl.identity.UserService.GetUserAndGroupsForOrg.
func (c *userServiceClient) GetUserAndGroupsForOrg(ctx context.Context, req *connect.Request[identity.GetUserAndGroupsForOrgRequest]) (*connect.Response[identity.GetUserAndGroupsForOrgResponse], error) {
	return c.getUserAndGroupsForOrg.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the cloudidl.identity.UserService service.
type UserServiceHandler interface {
	CreateUser(context.Context, *connect.Request[identity.CreateUserRequest]) (*connect.Response[identity.CreateUserResponse], error)
	GetUser(context.Context, *connect.Request[identity.GetUserRequest]) (*connect.Response[identity.GetUserResponse], error)
	DeleteUser(context.Context, *connect.Request[identity.DeleteUserRequest]) (*connect.Response[identity.DeleteUserResponse], error)
	ListUsers(context.Context, *connect.Request[identity.ListUsersRequest]) (*connect.Response[identity.ListUsersResponse], error)
	ListUsersCount(context.Context, *connect.Request[identity.ListUsersCountRequest]) (*connect.Response[identity.ListUsersCountResponse], error)
	GetUserAndGroupsForOrg(context.Context, *connect.Request[identity.GetUserAndGroupsForOrgRequest]) (*connect.Response[identity.GetUserAndGroupsForOrgResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(userServiceCreateUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceGetUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDeleteUserHandler := connect.NewUnaryHandler(
		UserServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(userServiceDeleteUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceListUsersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListUsersCountHandler := connect.NewUnaryHandler(
		UserServiceListUsersCountProcedure,
		svc.ListUsersCount,
		connect.WithSchema(userServiceListUsersCountMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserAndGroupsForOrgHandler := connect.NewUnaryHandler(
		UserServiceGetUserAndGroupsForOrgProcedure,
		svc.GetUserAndGroupsForOrg,
		connect.WithSchema(userServiceGetUserAndGroupsForOrgMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cloudidl.identity.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceDeleteUserProcedure:
			userServiceDeleteUserHandler.ServeHTTP(w, r)
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		case UserServiceListUsersCountProcedure:
			userServiceListUsersCountHandler.ServeHTTP(w, r)
		case UserServiceGetUserAndGroupsForOrgProcedure:
			userServiceGetUserAndGroupsForOrgHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[identity.CreateUserRequest]) (*connect.Response[identity.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[identity.GetUserRequest]) (*connect.Response[identity.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteUser(context.Context, *connect.Request[identity.DeleteUserRequest]) (*connect.Response[identity.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.UserService.DeleteUser is not implemented"))
}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[identity.ListUsersRequest]) (*connect.Response[identity.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.UserService.ListUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) ListUsersCount(context.Context, *connect.Request[identity.ListUsersCountRequest]) (*connect.Response[identity.ListUsersCountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.UserService.ListUsersCount is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUserAndGroupsForOrg(context.Context, *connect.Request[identity.GetUserAndGroupsForOrgRequest]) (*connect.Response[identity.GetUserAndGroupsForOrgResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.UserService.GetUserAndGroupsForOrg is not implemented"))
}
