// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/app_service.proto

package identityconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	identity "github.com/unionai/cloud/gen/pb-go/identity"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AppsServiceName is the fully-qualified name of the AppsService service.
	AppsServiceName = "cloudidl.identity.AppsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AppsServiceCreateProcedure is the fully-qualified name of the AppsService's Create RPC.
	AppsServiceCreateProcedure = "/cloudidl.identity.AppsService/Create"
	// AppsServiceGetProcedure is the fully-qualified name of the AppsService's Get RPC.
	AppsServiceGetProcedure = "/cloudidl.identity.AppsService/Get"
	// AppsServiceUpdateProcedure is the fully-qualified name of the AppsService's Update RPC.
	AppsServiceUpdateProcedure = "/cloudidl.identity.AppsService/Update"
	// AppsServiceDeleteProcedure is the fully-qualified name of the AppsService's Delete RPC.
	AppsServiceDeleteProcedure = "/cloudidl.identity.AppsService/Delete"
	// AppsServiceListProcedure is the fully-qualified name of the AppsService's List RPC.
	AppsServiceListProcedure = "/cloudidl.identity.AppsService/List"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	appsServiceServiceDescriptor      = identity.File_identity_app_service_proto.Services().ByName("AppsService")
	appsServiceCreateMethodDescriptor = appsServiceServiceDescriptor.Methods().ByName("Create")
	appsServiceGetMethodDescriptor    = appsServiceServiceDescriptor.Methods().ByName("Get")
	appsServiceUpdateMethodDescriptor = appsServiceServiceDescriptor.Methods().ByName("Update")
	appsServiceDeleteMethodDescriptor = appsServiceServiceDescriptor.Methods().ByName("Delete")
	appsServiceListMethodDescriptor   = appsServiceServiceDescriptor.Methods().ByName("List")
)

// AppsServiceClient is a client for the cloudidl.identity.AppsService service.
type AppsServiceClient interface {
	Create(context.Context, *connect.Request[identity.CreateAppRequest]) (*connect.Response[identity.CreateAppResponse], error)
	Get(context.Context, *connect.Request[identity.GetAppRequest]) (*connect.Response[identity.GetAppResponse], error)
	Update(context.Context, *connect.Request[identity.UpdateAppRequest]) (*connect.Response[identity.UpdateAppResponse], error)
	Delete(context.Context, *connect.Request[identity.DeleteAppRequest]) (*connect.Response[identity.DeleteAppResponse], error)
	List(context.Context, *connect.Request[identity.ListAppsRequest]) (*connect.Response[identity.ListAppsResponse], error)
}

// NewAppsServiceClient constructs a client for the cloudidl.identity.AppsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAppsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AppsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &appsServiceClient{
		create: connect.NewClient[identity.CreateAppRequest, identity.CreateAppResponse](
			httpClient,
			baseURL+AppsServiceCreateProcedure,
			connect.WithSchema(appsServiceCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[identity.GetAppRequest, identity.GetAppResponse](
			httpClient,
			baseURL+AppsServiceGetProcedure,
			connect.WithSchema(appsServiceGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[identity.UpdateAppRequest, identity.UpdateAppResponse](
			httpClient,
			baseURL+AppsServiceUpdateProcedure,
			connect.WithSchema(appsServiceUpdateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[identity.DeleteAppRequest, identity.DeleteAppResponse](
			httpClient,
			baseURL+AppsServiceDeleteProcedure,
			connect.WithSchema(appsServiceDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[identity.ListAppsRequest, identity.ListAppsResponse](
			httpClient,
			baseURL+AppsServiceListProcedure,
			connect.WithSchema(appsServiceListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// appsServiceClient implements AppsServiceClient.
type appsServiceClient struct {
	create *connect.Client[identity.CreateAppRequest, identity.CreateAppResponse]
	get    *connect.Client[identity.GetAppRequest, identity.GetAppResponse]
	update *connect.Client[identity.UpdateAppRequest, identity.UpdateAppResponse]
	delete *connect.Client[identity.DeleteAppRequest, identity.DeleteAppResponse]
	list   *connect.Client[identity.ListAppsRequest, identity.ListAppsResponse]
}

// Create calls cloudidl.identity.AppsService.Create.
func (c *appsServiceClient) Create(ctx context.Context, req *connect.Request[identity.CreateAppRequest]) (*connect.Response[identity.CreateAppResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Get calls cloudidl.identity.AppsService.Get.
func (c *appsServiceClient) Get(ctx context.Context, req *connect.Request[identity.GetAppRequest]) (*connect.Response[identity.GetAppResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Update calls cloudidl.identity.AppsService.Update.
func (c *appsServiceClient) Update(ctx context.Context, req *connect.Request[identity.UpdateAppRequest]) (*connect.Response[identity.UpdateAppResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls cloudidl.identity.AppsService.Delete.
func (c *appsServiceClient) Delete(ctx context.Context, req *connect.Request[identity.DeleteAppRequest]) (*connect.Response[identity.DeleteAppResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls cloudidl.identity.AppsService.List.
func (c *appsServiceClient) List(ctx context.Context, req *connect.Request[identity.ListAppsRequest]) (*connect.Response[identity.ListAppsResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// AppsServiceHandler is an implementation of the cloudidl.identity.AppsService service.
type AppsServiceHandler interface {
	Create(context.Context, *connect.Request[identity.CreateAppRequest]) (*connect.Response[identity.CreateAppResponse], error)
	Get(context.Context, *connect.Request[identity.GetAppRequest]) (*connect.Response[identity.GetAppResponse], error)
	Update(context.Context, *connect.Request[identity.UpdateAppRequest]) (*connect.Response[identity.UpdateAppResponse], error)
	Delete(context.Context, *connect.Request[identity.DeleteAppRequest]) (*connect.Response[identity.DeleteAppResponse], error)
	List(context.Context, *connect.Request[identity.ListAppsRequest]) (*connect.Response[identity.ListAppsResponse], error)
}

// NewAppsServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAppsServiceHandler(svc AppsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	appsServiceCreateHandler := connect.NewUnaryHandler(
		AppsServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(appsServiceCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	appsServiceGetHandler := connect.NewUnaryHandler(
		AppsServiceGetProcedure,
		svc.Get,
		connect.WithSchema(appsServiceGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	appsServiceUpdateHandler := connect.NewUnaryHandler(
		AppsServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(appsServiceUpdateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	appsServiceDeleteHandler := connect.NewUnaryHandler(
		AppsServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(appsServiceDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	appsServiceListHandler := connect.NewUnaryHandler(
		AppsServiceListProcedure,
		svc.List,
		connect.WithSchema(appsServiceListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cloudidl.identity.AppsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AppsServiceCreateProcedure:
			appsServiceCreateHandler.ServeHTTP(w, r)
		case AppsServiceGetProcedure:
			appsServiceGetHandler.ServeHTTP(w, r)
		case AppsServiceUpdateProcedure:
			appsServiceUpdateHandler.ServeHTTP(w, r)
		case AppsServiceDeleteProcedure:
			appsServiceDeleteHandler.ServeHTTP(w, r)
		case AppsServiceListProcedure:
			appsServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAppsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAppsServiceHandler struct{}

func (UnimplementedAppsServiceHandler) Create(context.Context, *connect.Request[identity.CreateAppRequest]) (*connect.Response[identity.CreateAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.AppsService.Create is not implemented"))
}

func (UnimplementedAppsServiceHandler) Get(context.Context, *connect.Request[identity.GetAppRequest]) (*connect.Response[identity.GetAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.AppsService.Get is not implemented"))
}

func (UnimplementedAppsServiceHandler) Update(context.Context, *connect.Request[identity.UpdateAppRequest]) (*connect.Response[identity.UpdateAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.AppsService.Update is not implemented"))
}

func (UnimplementedAppsServiceHandler) Delete(context.Context, *connect.Request[identity.DeleteAppRequest]) (*connect.Response[identity.DeleteAppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.AppsService.Delete is not implemented"))
}

func (UnimplementedAppsServiceHandler) List(context.Context, *connect.Request[identity.ListAppsRequest]) (*connect.Response[identity.ListAppsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.AppsService.List is not implemented"))
}
