// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/selfserve_service.proto

package identityconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	identity "github.com/unionai/cloud/gen/pb-go/identity"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SelfServeName is the fully-qualified name of the SelfServe service.
	SelfServeName = "cloudidl.identity.SelfServe"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SelfServeRegisterProcedure is the fully-qualified name of the SelfServe's Register RPC.
	SelfServeRegisterProcedure = "/cloudidl.identity.SelfServe/Register"
	// SelfServeDeRegisterProcedure is the fully-qualified name of the SelfServe's DeRegister RPC.
	SelfServeDeRegisterProcedure = "/cloudidl.identity.SelfServe/DeRegister"
	// SelfServeOffboardProcedure is the fully-qualified name of the SelfServe's Offboard RPC.
	SelfServeOffboardProcedure = "/cloudidl.identity.SelfServe/Offboard"
	// SelfServeProvisionProcedure is the fully-qualified name of the SelfServe's Provision RPC.
	SelfServeProvisionProcedure = "/cloudidl.identity.SelfServe/Provision"
	// SelfServeUpdateProcedure is the fully-qualified name of the SelfServe's Update RPC.
	SelfServeUpdateProcedure = "/cloudidl.identity.SelfServe/Update"
	// SelfServeBatchUpdateProcedure is the fully-qualified name of the SelfServe's BatchUpdate RPC.
	SelfServeBatchUpdateProcedure = "/cloudidl.identity.SelfServe/BatchUpdate"
	// SelfServeProvisionOrgProcedure is the fully-qualified name of the SelfServe's ProvisionOrg RPC.
	SelfServeProvisionOrgProcedure = "/cloudidl.identity.SelfServe/ProvisionOrg"
	// SelfServeProvisionDataplaneResourcesProcedure is the fully-qualified name of the SelfServe's
	// ProvisionDataplaneResources RPC.
	SelfServeProvisionDataplaneResourcesProcedure = "/cloudidl.identity.SelfServe/ProvisionDataplaneResources"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	selfServeServiceDescriptor                           = identity.File_identity_selfserve_service_proto.Services().ByName("SelfServe")
	selfServeRegisterMethodDescriptor                    = selfServeServiceDescriptor.Methods().ByName("Register")
	selfServeDeRegisterMethodDescriptor                  = selfServeServiceDescriptor.Methods().ByName("DeRegister")
	selfServeOffboardMethodDescriptor                    = selfServeServiceDescriptor.Methods().ByName("Offboard")
	selfServeProvisionMethodDescriptor                   = selfServeServiceDescriptor.Methods().ByName("Provision")
	selfServeUpdateMethodDescriptor                      = selfServeServiceDescriptor.Methods().ByName("Update")
	selfServeBatchUpdateMethodDescriptor                 = selfServeServiceDescriptor.Methods().ByName("BatchUpdate")
	selfServeProvisionOrgMethodDescriptor                = selfServeServiceDescriptor.Methods().ByName("ProvisionOrg")
	selfServeProvisionDataplaneResourcesMethodDescriptor = selfServeServiceDescriptor.Methods().ByName("ProvisionDataplaneResources")
)

// SelfServeClient is a client for the cloudidl.identity.SelfServe service.
type SelfServeClient interface {
	Register(context.Context, *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error)
	// DeRegister is used to deregister a service from the selfserve system and uses the same input as Register.
	DeRegister(context.Context, *connect.Request[identity.SelfServeDeregisterRequest]) (*connect.Response[identity.SelfServeDeregisterResponse], error)
	// Offboard is used for offboarding the user and currently this gives the user Viewer permissions in his own org.
	Offboard(context.Context, *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error)
	// Provision is used to provision a users resources and not change their state
	Provision(context.Context, *connect.Request[identity.SelfServeProvisionRequest]) (*connect.Response[identity.SelfServeProvisionResponse], error)
	// Update is used to change the state of the user and not provision any resources
	Update(context.Context, *connect.Request[identity.SelfServeUpdateRequest]) (*connect.Response[identity.SelfServeUpdateResponse], error)
	// BatchUpdate is used to update multiple users at once
	BatchUpdate(context.Context, *connect.Request[identity.SelfServeBatchUpdateRequest]) (*connect.Response[identity.SelfServeBatchUpdateResponse], error)
	ProvisionOrg(context.Context, *connect.Request[identity.SelfServeProvisionOrgRequest]) (*connect.Response[identity.SelfServeProvisionOrgResponse], error)
	ProvisionDataplaneResources(context.Context, *connect.Request[identity.SelfServeProvisionDataplaneResourcesRequest]) (*connect.Response[identity.SelfServeProvisionDataplaneResourcesResponse], error)
}

// NewSelfServeClient constructs a client for the cloudidl.identity.SelfServe service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSelfServeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SelfServeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &selfServeClient{
		register: connect.NewClient[identity.SelfServeRegisterRequest, identity.SelfServeRegisterResponse](
			httpClient,
			baseURL+SelfServeRegisterProcedure,
			connect.WithSchema(selfServeRegisterMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deRegister: connect.NewClient[identity.SelfServeDeregisterRequest, identity.SelfServeDeregisterResponse](
			httpClient,
			baseURL+SelfServeDeRegisterProcedure,
			connect.WithSchema(selfServeDeRegisterMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		offboard: connect.NewClient[identity.SelfServeRegisterRequest, identity.SelfServeRegisterResponse](
			httpClient,
			baseURL+SelfServeOffboardProcedure,
			connect.WithSchema(selfServeOffboardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		provision: connect.NewClient[identity.SelfServeProvisionRequest, identity.SelfServeProvisionResponse](
			httpClient,
			baseURL+SelfServeProvisionProcedure,
			connect.WithSchema(selfServeProvisionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[identity.SelfServeUpdateRequest, identity.SelfServeUpdateResponse](
			httpClient,
			baseURL+SelfServeUpdateProcedure,
			connect.WithSchema(selfServeUpdateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		batchUpdate: connect.NewClient[identity.SelfServeBatchUpdateRequest, identity.SelfServeBatchUpdateResponse](
			httpClient,
			baseURL+SelfServeBatchUpdateProcedure,
			connect.WithSchema(selfServeBatchUpdateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		provisionOrg: connect.NewClient[identity.SelfServeProvisionOrgRequest, identity.SelfServeProvisionOrgResponse](
			httpClient,
			baseURL+SelfServeProvisionOrgProcedure,
			connect.WithSchema(selfServeProvisionOrgMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		provisionDataplaneResources: connect.NewClient[identity.SelfServeProvisionDataplaneResourcesRequest, identity.SelfServeProvisionDataplaneResourcesResponse](
			httpClient,
			baseURL+SelfServeProvisionDataplaneResourcesProcedure,
			connect.WithSchema(selfServeProvisionDataplaneResourcesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// selfServeClient implements SelfServeClient.
type selfServeClient struct {
	register                    *connect.Client[identity.SelfServeRegisterRequest, identity.SelfServeRegisterResponse]
	deRegister                  *connect.Client[identity.SelfServeDeregisterRequest, identity.SelfServeDeregisterResponse]
	offboard                    *connect.Client[identity.SelfServeRegisterRequest, identity.SelfServeRegisterResponse]
	provision                   *connect.Client[identity.SelfServeProvisionRequest, identity.SelfServeProvisionResponse]
	update                      *connect.Client[identity.SelfServeUpdateRequest, identity.SelfServeUpdateResponse]
	batchUpdate                 *connect.Client[identity.SelfServeBatchUpdateRequest, identity.SelfServeBatchUpdateResponse]
	provisionOrg                *connect.Client[identity.SelfServeProvisionOrgRequest, identity.SelfServeProvisionOrgResponse]
	provisionDataplaneResources *connect.Client[identity.SelfServeProvisionDataplaneResourcesRequest, identity.SelfServeProvisionDataplaneResourcesResponse]
}

// Register calls cloudidl.identity.SelfServe.Register.
func (c *selfServeClient) Register(ctx context.Context, req *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// DeRegister calls cloudidl.identity.SelfServe.DeRegister.
func (c *selfServeClient) DeRegister(ctx context.Context, req *connect.Request[identity.SelfServeDeregisterRequest]) (*connect.Response[identity.SelfServeDeregisterResponse], error) {
	return c.deRegister.CallUnary(ctx, req)
}

// Offboard calls cloudidl.identity.SelfServe.Offboard.
func (c *selfServeClient) Offboard(ctx context.Context, req *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error) {
	return c.offboard.CallUnary(ctx, req)
}

// Provision calls cloudidl.identity.SelfServe.Provision.
func (c *selfServeClient) Provision(ctx context.Context, req *connect.Request[identity.SelfServeProvisionRequest]) (*connect.Response[identity.SelfServeProvisionResponse], error) {
	return c.provision.CallUnary(ctx, req)
}

// Update calls cloudidl.identity.SelfServe.Update.
func (c *selfServeClient) Update(ctx context.Context, req *connect.Request[identity.SelfServeUpdateRequest]) (*connect.Response[identity.SelfServeUpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// BatchUpdate calls cloudidl.identity.SelfServe.BatchUpdate.
func (c *selfServeClient) BatchUpdate(ctx context.Context, req *connect.Request[identity.SelfServeBatchUpdateRequest]) (*connect.Response[identity.SelfServeBatchUpdateResponse], error) {
	return c.batchUpdate.CallUnary(ctx, req)
}

// ProvisionOrg calls cloudidl.identity.SelfServe.ProvisionOrg.
func (c *selfServeClient) ProvisionOrg(ctx context.Context, req *connect.Request[identity.SelfServeProvisionOrgRequest]) (*connect.Response[identity.SelfServeProvisionOrgResponse], error) {
	return c.provisionOrg.CallUnary(ctx, req)
}

// ProvisionDataplaneResources calls cloudidl.identity.SelfServe.ProvisionDataplaneResources.
func (c *selfServeClient) ProvisionDataplaneResources(ctx context.Context, req *connect.Request[identity.SelfServeProvisionDataplaneResourcesRequest]) (*connect.Response[identity.SelfServeProvisionDataplaneResourcesResponse], error) {
	return c.provisionDataplaneResources.CallUnary(ctx, req)
}

// SelfServeHandler is an implementation of the cloudidl.identity.SelfServe service.
type SelfServeHandler interface {
	Register(context.Context, *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error)
	// DeRegister is used to deregister a service from the selfserve system and uses the same input as Register.
	DeRegister(context.Context, *connect.Request[identity.SelfServeDeregisterRequest]) (*connect.Response[identity.SelfServeDeregisterResponse], error)
	// Offboard is used for offboarding the user and currently this gives the user Viewer permissions in his own org.
	Offboard(context.Context, *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error)
	// Provision is used to provision a users resources and not change their state
	Provision(context.Context, *connect.Request[identity.SelfServeProvisionRequest]) (*connect.Response[identity.SelfServeProvisionResponse], error)
	// Update is used to change the state of the user and not provision any resources
	Update(context.Context, *connect.Request[identity.SelfServeUpdateRequest]) (*connect.Response[identity.SelfServeUpdateResponse], error)
	// BatchUpdate is used to update multiple users at once
	BatchUpdate(context.Context, *connect.Request[identity.SelfServeBatchUpdateRequest]) (*connect.Response[identity.SelfServeBatchUpdateResponse], error)
	ProvisionOrg(context.Context, *connect.Request[identity.SelfServeProvisionOrgRequest]) (*connect.Response[identity.SelfServeProvisionOrgResponse], error)
	ProvisionDataplaneResources(context.Context, *connect.Request[identity.SelfServeProvisionDataplaneResourcesRequest]) (*connect.Response[identity.SelfServeProvisionDataplaneResourcesResponse], error)
}

// NewSelfServeHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSelfServeHandler(svc SelfServeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	selfServeRegisterHandler := connect.NewUnaryHandler(
		SelfServeRegisterProcedure,
		svc.Register,
		connect.WithSchema(selfServeRegisterMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeDeRegisterHandler := connect.NewUnaryHandler(
		SelfServeDeRegisterProcedure,
		svc.DeRegister,
		connect.WithSchema(selfServeDeRegisterMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeOffboardHandler := connect.NewUnaryHandler(
		SelfServeOffboardProcedure,
		svc.Offboard,
		connect.WithSchema(selfServeOffboardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeProvisionHandler := connect.NewUnaryHandler(
		SelfServeProvisionProcedure,
		svc.Provision,
		connect.WithSchema(selfServeProvisionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeUpdateHandler := connect.NewUnaryHandler(
		SelfServeUpdateProcedure,
		svc.Update,
		connect.WithSchema(selfServeUpdateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeBatchUpdateHandler := connect.NewUnaryHandler(
		SelfServeBatchUpdateProcedure,
		svc.BatchUpdate,
		connect.WithSchema(selfServeBatchUpdateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeProvisionOrgHandler := connect.NewUnaryHandler(
		SelfServeProvisionOrgProcedure,
		svc.ProvisionOrg,
		connect.WithSchema(selfServeProvisionOrgMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	selfServeProvisionDataplaneResourcesHandler := connect.NewUnaryHandler(
		SelfServeProvisionDataplaneResourcesProcedure,
		svc.ProvisionDataplaneResources,
		connect.WithSchema(selfServeProvisionDataplaneResourcesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cloudidl.identity.SelfServe/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SelfServeRegisterProcedure:
			selfServeRegisterHandler.ServeHTTP(w, r)
		case SelfServeDeRegisterProcedure:
			selfServeDeRegisterHandler.ServeHTTP(w, r)
		case SelfServeOffboardProcedure:
			selfServeOffboardHandler.ServeHTTP(w, r)
		case SelfServeProvisionProcedure:
			selfServeProvisionHandler.ServeHTTP(w, r)
		case SelfServeUpdateProcedure:
			selfServeUpdateHandler.ServeHTTP(w, r)
		case SelfServeBatchUpdateProcedure:
			selfServeBatchUpdateHandler.ServeHTTP(w, r)
		case SelfServeProvisionOrgProcedure:
			selfServeProvisionOrgHandler.ServeHTTP(w, r)
		case SelfServeProvisionDataplaneResourcesProcedure:
			selfServeProvisionDataplaneResourcesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSelfServeHandler returns CodeUnimplemented from all methods.
type UnimplementedSelfServeHandler struct{}

func (UnimplementedSelfServeHandler) Register(context.Context, *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.Register is not implemented"))
}

func (UnimplementedSelfServeHandler) DeRegister(context.Context, *connect.Request[identity.SelfServeDeregisterRequest]) (*connect.Response[identity.SelfServeDeregisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.DeRegister is not implemented"))
}

func (UnimplementedSelfServeHandler) Offboard(context.Context, *connect.Request[identity.SelfServeRegisterRequest]) (*connect.Response[identity.SelfServeRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.Offboard is not implemented"))
}

func (UnimplementedSelfServeHandler) Provision(context.Context, *connect.Request[identity.SelfServeProvisionRequest]) (*connect.Response[identity.SelfServeProvisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.Provision is not implemented"))
}

func (UnimplementedSelfServeHandler) Update(context.Context, *connect.Request[identity.SelfServeUpdateRequest]) (*connect.Response[identity.SelfServeUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.Update is not implemented"))
}

func (UnimplementedSelfServeHandler) BatchUpdate(context.Context, *connect.Request[identity.SelfServeBatchUpdateRequest]) (*connect.Response[identity.SelfServeBatchUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.BatchUpdate is not implemented"))
}

func (UnimplementedSelfServeHandler) ProvisionOrg(context.Context, *connect.Request[identity.SelfServeProvisionOrgRequest]) (*connect.Response[identity.SelfServeProvisionOrgResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.ProvisionOrg is not implemented"))
}

func (UnimplementedSelfServeHandler) ProvisionDataplaneResources(context.Context, *connect.Request[identity.SelfServeProvisionDataplaneResourcesRequest]) (*connect.Response[identity.SelfServeProvisionDataplaneResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.identity.SelfServe.ProvisionDataplaneResources is not implemented"))
}
