// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/quantity.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DisplayQuantity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DisplayQuantity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DisplayQuantity with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DisplayQuantityMultiError, or nil if none found.
func (m *DisplayQuantity) ValidateAll() error {
	return m.validate(true)
}

func (m *DisplayQuantity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Unit

	if len(errors) > 0 {
		return DisplayQuantityMultiError(errors)
	}

	return nil
}

// DisplayQuantityMultiError is an error wrapping multiple validation errors
// returned by DisplayQuantity.ValidateAll() if the designated constraints
// aren't met.
type DisplayQuantityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DisplayQuantityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DisplayQuantityMultiError) AllErrors() []error { return m }

// DisplayQuantityValidationError is the validation error returned by
// DisplayQuantity.Validate if the designated constraints aren't met.
type DisplayQuantityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DisplayQuantityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DisplayQuantityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DisplayQuantityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DisplayQuantityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DisplayQuantityValidationError) ErrorName() string { return "DisplayQuantityValidationError" }

// Error satisfies the builtin error interface
func (e DisplayQuantityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDisplayQuantity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DisplayQuantityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DisplayQuantityValidationError{}
