// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: identity/identity_service.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IdentityService_ListIdentitiesBySubject_FullMethodName = "/cloudidl.identity.IdentityService/ListIdentitiesBySubject"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	// Lists identities (apps and users) for the input subjects for the given organization.
	ListIdentitiesBySubject(ctx context.Context, in *ListIdentitiesBySubjectRequest, opts ...grpc.CallOption) (*ListIdentitiesBySubjectResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) ListIdentitiesBySubject(ctx context.Context, in *ListIdentitiesBySubjectRequest, opts ...grpc.CallOption) (*ListIdentitiesBySubjectResponse, error) {
	out := new(ListIdentitiesBySubjectResponse)
	err := c.cc.Invoke(ctx, IdentityService_ListIdentitiesBySubject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations should embed UnimplementedIdentityServiceServer
// for forward compatibility
type IdentityServiceServer interface {
	// Lists identities (apps and users) for the input subjects for the given organization.
	ListIdentitiesBySubject(context.Context, *ListIdentitiesBySubjectRequest) (*ListIdentitiesBySubjectResponse, error)
}

// UnimplementedIdentityServiceServer should be embedded to have forward compatible implementations.
type UnimplementedIdentityServiceServer struct {
}

func (UnimplementedIdentityServiceServer) ListIdentitiesBySubject(context.Context, *ListIdentitiesBySubjectRequest) (*ListIdentitiesBySubjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIdentitiesBySubject not implemented")
}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_ListIdentitiesBySubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentitiesBySubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ListIdentitiesBySubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ListIdentitiesBySubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ListIdentitiesBySubject(ctx, req.(*ListIdentitiesBySubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudidl.identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIdentitiesBySubject",
			Handler:    _IdentityService_ListIdentitiesBySubject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/identity_service.proto",
}
