// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: cluster/managed_payload.proto

package cluster

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/unionai/cloud/gen/pb-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagedClusterServiceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *ManagedClusterInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ManagedClusterServiceCreateRequest) Reset() {
	*x = ManagedClusterServiceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceCreateRequest) ProtoMessage() {}

func (x *ManagedClusterServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedClusterServiceCreateRequest) GetInfo() *ManagedClusterInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ManagedClusterServiceCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ManagedClusterServiceCreateResponse) Reset() {
	*x = ManagedClusterServiceCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceCreateResponse) ProtoMessage() {}

func (x *ManagedClusterServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{1}
}

type ManagedClusterServiceGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *common.ManagedClusterIdentifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ManagedClusterServiceGetRequest) Reset() {
	*x = ManagedClusterServiceGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceGetRequest) ProtoMessage() {}

func (x *ManagedClusterServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{2}
}

func (x *ManagedClusterServiceGetRequest) GetId() *common.ManagedClusterIdentifier {
	if x != nil {
		return x.Id
	}
	return nil
}

type ManagedClusterServiceGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *ManagedCluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *ManagedClusterServiceGetResponse) Reset() {
	*x = ManagedClusterServiceGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceGetResponse) ProtoMessage() {}

func (x *ManagedClusterServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{3}
}

func (x *ManagedClusterServiceGetResponse) GetCluster() *ManagedCluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type ManagedClusterServiceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *common.ListRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Optional, tenant for this request
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ManagedClusterServiceListRequest) Reset() {
	*x = ManagedClusterServiceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceListRequest) ProtoMessage() {}

func (x *ManagedClusterServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceListRequest.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceListRequest) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{4}
}

func (x *ManagedClusterServiceListRequest) GetRequest() *common.ListRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ManagedClusterServiceListRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ManagedClusterServiceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clusters []*ManagedCluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	// In the case of multiple pages of results, the server-provided token can be used to fetch the next page
	// in a query. If there are no more results, this value will be empty.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ManagedClusterServiceListResponse) Reset() {
	*x = ManagedClusterServiceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceListResponse) ProtoMessage() {}

func (x *ManagedClusterServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceListResponse.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceListResponse) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{5}
}

func (x *ManagedClusterServiceListResponse) GetClusters() []*ManagedCluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ManagedClusterServiceListResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ManagedClusterServiceListDisplayInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *common.ListRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ManagedClusterServiceListDisplayInfoRequest) Reset() {
	*x = ManagedClusterServiceListDisplayInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceListDisplayInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceListDisplayInfoRequest) ProtoMessage() {}

func (x *ManagedClusterServiceListDisplayInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceListDisplayInfoRequest.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceListDisplayInfoRequest) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{6}
}

func (x *ManagedClusterServiceListDisplayInfoRequest) GetRequest() *common.ListRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ManagedClusterServiceListDisplayInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clusters []*ManagedCluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	// In the case of multiple pages of results, the server-provided token can be used to fetch the next page
	// in a query. If there are no more results, this value will be empty.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ManagedClusterServiceListDisplayInfoResponse) Reset() {
	*x = ManagedClusterServiceListDisplayInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceListDisplayInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceListDisplayInfoResponse) ProtoMessage() {}

func (x *ManagedClusterServiceListDisplayInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceListDisplayInfoResponse.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceListDisplayInfoResponse) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{7}
}

func (x *ManagedClusterServiceListDisplayInfoResponse) GetClusters() []*ManagedCluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ManagedClusterServiceListDisplayInfoResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ManagedClusterServiceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *common.ManagedClusterIdentifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ManagedClusterServiceDeleteRequest) Reset() {
	*x = ManagedClusterServiceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceDeleteRequest) ProtoMessage() {}

func (x *ManagedClusterServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{8}
}

func (x *ManagedClusterServiceDeleteRequest) GetId() *common.ManagedClusterIdentifier {
	if x != nil {
		return x.Id
	}
	return nil
}

type ManagedClusterServiceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ManagedClusterServiceDeleteResponse) Reset() {
	*x = ManagedClusterServiceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_managed_payload_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedClusterServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedClusterServiceDeleteResponse) ProtoMessage() {}

func (x *ManagedClusterServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_managed_payload_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedClusterServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ManagedClusterServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_cluster_managed_payload_proto_rawDescGZIP(), []int{9}
}

var File_cluster_managed_payload_proto protoreflect.FileDescriptor

var file_cluster_managed_payload_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x5f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x22,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x40, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x25, 0x0a, 0x23, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x64, 0x0a, 0x1f, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x5e, 0x0a, 0x20, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64,
	0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x6e, 0x0a, 0x20, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64,
	0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x22, 0x77, 0x0a, 0x21, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x08, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x65, 0x0a, 0x2b, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x82, 0x01, 0x0a, 0x2c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x67, 0x0a, 0x22, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x25, 0x0a, 0x23, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xba, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42,
	0x13, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x61, 0x69, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x43, 0x43, 0x58, 0xaa, 0x02, 0x10, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x69, 0x64, 0x6c, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0xca, 0x02, 0x10,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x5c, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0xe2, 0x02, 0x1c, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x5c, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x11, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x64, 0x6c, 0x3a, 0x3a, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cluster_managed_payload_proto_rawDescOnce sync.Once
	file_cluster_managed_payload_proto_rawDescData = file_cluster_managed_payload_proto_rawDesc
)

func file_cluster_managed_payload_proto_rawDescGZIP() []byte {
	file_cluster_managed_payload_proto_rawDescOnce.Do(func() {
		file_cluster_managed_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_managed_payload_proto_rawDescData)
	})
	return file_cluster_managed_payload_proto_rawDescData
}

var file_cluster_managed_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cluster_managed_payload_proto_goTypes = []interface{}{
	(*ManagedClusterServiceCreateRequest)(nil),           // 0: cloudidl.cluster.ManagedClusterServiceCreateRequest
	(*ManagedClusterServiceCreateResponse)(nil),          // 1: cloudidl.cluster.ManagedClusterServiceCreateResponse
	(*ManagedClusterServiceGetRequest)(nil),              // 2: cloudidl.cluster.ManagedClusterServiceGetRequest
	(*ManagedClusterServiceGetResponse)(nil),             // 3: cloudidl.cluster.ManagedClusterServiceGetResponse
	(*ManagedClusterServiceListRequest)(nil),             // 4: cloudidl.cluster.ManagedClusterServiceListRequest
	(*ManagedClusterServiceListResponse)(nil),            // 5: cloudidl.cluster.ManagedClusterServiceListResponse
	(*ManagedClusterServiceListDisplayInfoRequest)(nil),  // 6: cloudidl.cluster.ManagedClusterServiceListDisplayInfoRequest
	(*ManagedClusterServiceListDisplayInfoResponse)(nil), // 7: cloudidl.cluster.ManagedClusterServiceListDisplayInfoResponse
	(*ManagedClusterServiceDeleteRequest)(nil),           // 8: cloudidl.cluster.ManagedClusterServiceDeleteRequest
	(*ManagedClusterServiceDeleteResponse)(nil),          // 9: cloudidl.cluster.ManagedClusterServiceDeleteResponse
	(*ManagedClusterInfo)(nil),                           // 10: cloudidl.cluster.ManagedClusterInfo
	(*common.ManagedClusterIdentifier)(nil),              // 11: cloudidl.common.ManagedClusterIdentifier
	(*ManagedCluster)(nil),                               // 12: cloudidl.cluster.ManagedCluster
	(*common.ListRequest)(nil),                           // 13: cloudidl.common.ListRequest
}
var file_cluster_managed_payload_proto_depIdxs = []int32{
	10, // 0: cloudidl.cluster.ManagedClusterServiceCreateRequest.info:type_name -> cloudidl.cluster.ManagedClusterInfo
	11, // 1: cloudidl.cluster.ManagedClusterServiceGetRequest.id:type_name -> cloudidl.common.ManagedClusterIdentifier
	12, // 2: cloudidl.cluster.ManagedClusterServiceGetResponse.cluster:type_name -> cloudidl.cluster.ManagedCluster
	13, // 3: cloudidl.cluster.ManagedClusterServiceListRequest.request:type_name -> cloudidl.common.ListRequest
	12, // 4: cloudidl.cluster.ManagedClusterServiceListResponse.clusters:type_name -> cloudidl.cluster.ManagedCluster
	13, // 5: cloudidl.cluster.ManagedClusterServiceListDisplayInfoRequest.request:type_name -> cloudidl.common.ListRequest
	12, // 6: cloudidl.cluster.ManagedClusterServiceListDisplayInfoResponse.clusters:type_name -> cloudidl.cluster.ManagedCluster
	11, // 7: cloudidl.cluster.ManagedClusterServiceDeleteRequest.id:type_name -> cloudidl.common.ManagedClusterIdentifier
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cluster_managed_payload_proto_init() }
func file_cluster_managed_payload_proto_init() {
	if File_cluster_managed_payload_proto != nil {
		return
	}
	file_cluster_managed_definition_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cluster_managed_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceListDisplayInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceListDisplayInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_managed_payload_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedClusterServiceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_managed_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_managed_payload_proto_goTypes,
		DependencyIndexes: file_cluster_managed_payload_proto_depIdxs,
		MessageInfos:      file_cluster_managed_payload_proto_msgTypes,
	}.Build()
	File_cluster_managed_payload_proto = out.File
	file_cluster_managed_payload_proto_rawDesc = nil
	file_cluster_managed_payload_proto_goTypes = nil
	file_cluster_managed_payload_proto_depIdxs = nil
}
