// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cluster/nodepool_service.proto

package cluster

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClusterNodepoolService_UpsertNodepool_FullMethodName = "/cloudidl.cluster.ClusterNodepoolService/UpsertNodepool"
	ClusterNodepoolService_GetNodepool_FullMethodName    = "/cloudidl.cluster.ClusterNodepoolService/GetNodepool"
	ClusterNodepoolService_DeleteNodepool_FullMethodName = "/cloudidl.cluster.ClusterNodepoolService/DeleteNodepool"
	ClusterNodepoolService_ListNodepools_FullMethodName  = "/cloudidl.cluster.ClusterNodepoolService/ListNodepools"
)

// ClusterNodepoolServiceClient is the client API for ClusterNodepoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterNodepoolServiceClient interface {
	UpsertNodepool(ctx context.Context, in *UpsertNodepoolRequest, opts ...grpc.CallOption) (*UpsertNodepoolResponse, error)
	GetNodepool(ctx context.Context, in *GetNodepoolRequest, opts ...grpc.CallOption) (*GetNodepoolResponse, error)
	DeleteNodepool(ctx context.Context, in *DeleteNodepoolRequest, opts ...grpc.CallOption) (*DeleteNodepoolResponse, error)
	ListNodepools(ctx context.Context, in *ListNodepoolsRequest, opts ...grpc.CallOption) (*ListNodepoolsResponse, error)
}

type clusterNodepoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterNodepoolServiceClient(cc grpc.ClientConnInterface) ClusterNodepoolServiceClient {
	return &clusterNodepoolServiceClient{cc}
}

func (c *clusterNodepoolServiceClient) UpsertNodepool(ctx context.Context, in *UpsertNodepoolRequest, opts ...grpc.CallOption) (*UpsertNodepoolResponse, error) {
	out := new(UpsertNodepoolResponse)
	err := c.cc.Invoke(ctx, ClusterNodepoolService_UpsertNodepool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterNodepoolServiceClient) GetNodepool(ctx context.Context, in *GetNodepoolRequest, opts ...grpc.CallOption) (*GetNodepoolResponse, error) {
	out := new(GetNodepoolResponse)
	err := c.cc.Invoke(ctx, ClusterNodepoolService_GetNodepool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterNodepoolServiceClient) DeleteNodepool(ctx context.Context, in *DeleteNodepoolRequest, opts ...grpc.CallOption) (*DeleteNodepoolResponse, error) {
	out := new(DeleteNodepoolResponse)
	err := c.cc.Invoke(ctx, ClusterNodepoolService_DeleteNodepool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterNodepoolServiceClient) ListNodepools(ctx context.Context, in *ListNodepoolsRequest, opts ...grpc.CallOption) (*ListNodepoolsResponse, error) {
	out := new(ListNodepoolsResponse)
	err := c.cc.Invoke(ctx, ClusterNodepoolService_ListNodepools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterNodepoolServiceServer is the server API for ClusterNodepoolService service.
// All implementations should embed UnimplementedClusterNodepoolServiceServer
// for forward compatibility
type ClusterNodepoolServiceServer interface {
	UpsertNodepool(context.Context, *UpsertNodepoolRequest) (*UpsertNodepoolResponse, error)
	GetNodepool(context.Context, *GetNodepoolRequest) (*GetNodepoolResponse, error)
	DeleteNodepool(context.Context, *DeleteNodepoolRequest) (*DeleteNodepoolResponse, error)
	ListNodepools(context.Context, *ListNodepoolsRequest) (*ListNodepoolsResponse, error)
}

// UnimplementedClusterNodepoolServiceServer should be embedded to have forward compatible implementations.
type UnimplementedClusterNodepoolServiceServer struct {
}

func (UnimplementedClusterNodepoolServiceServer) UpsertNodepool(context.Context, *UpsertNodepoolRequest) (*UpsertNodepoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertNodepool not implemented")
}
func (UnimplementedClusterNodepoolServiceServer) GetNodepool(context.Context, *GetNodepoolRequest) (*GetNodepoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodepool not implemented")
}
func (UnimplementedClusterNodepoolServiceServer) DeleteNodepool(context.Context, *DeleteNodepoolRequest) (*DeleteNodepoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNodepool not implemented")
}
func (UnimplementedClusterNodepoolServiceServer) ListNodepools(context.Context, *ListNodepoolsRequest) (*ListNodepoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodepools not implemented")
}

// UnsafeClusterNodepoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterNodepoolServiceServer will
// result in compilation errors.
type UnsafeClusterNodepoolServiceServer interface {
	mustEmbedUnimplementedClusterNodepoolServiceServer()
}

func RegisterClusterNodepoolServiceServer(s grpc.ServiceRegistrar, srv ClusterNodepoolServiceServer) {
	s.RegisterService(&ClusterNodepoolService_ServiceDesc, srv)
}

func _ClusterNodepoolService_UpsertNodepool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNodepoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterNodepoolServiceServer).UpsertNodepool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterNodepoolService_UpsertNodepool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterNodepoolServiceServer).UpsertNodepool(ctx, req.(*UpsertNodepoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterNodepoolService_GetNodepool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodepoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterNodepoolServiceServer).GetNodepool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterNodepoolService_GetNodepool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterNodepoolServiceServer).GetNodepool(ctx, req.(*GetNodepoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterNodepoolService_DeleteNodepool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodepoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterNodepoolServiceServer).DeleteNodepool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterNodepoolService_DeleteNodepool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterNodepoolServiceServer).DeleteNodepool(ctx, req.(*DeleteNodepoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterNodepoolService_ListNodepools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodepoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterNodepoolServiceServer).ListNodepools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterNodepoolService_ListNodepools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterNodepoolServiceServer).ListNodepools(ctx, req.(*ListNodepoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterNodepoolService_ServiceDesc is the grpc.ServiceDesc for ClusterNodepoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterNodepoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudidl.cluster.ClusterNodepoolService",
	HandlerType: (*ClusterNodepoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertNodepool",
			Handler:    _ClusterNodepoolService_UpsertNodepool_Handler,
		},
		{
			MethodName: "GetNodepool",
			Handler:    _ClusterNodepoolService_GetNodepool_Handler,
		},
		{
			MethodName: "DeleteNodepool",
			Handler:    _ClusterNodepoolService_DeleteNodepool_Handler,
		},
		{
			MethodName: "ListNodepools",
			Handler:    _ClusterNodepoolService_ListNodepools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster/nodepool_service.proto",
}
