// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cluster/nodepool_payload.proto

package cluster

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpsertNodepoolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertNodepoolRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertNodepoolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertNodepoolRequestMultiError, or nil if none found.
func (m *UpsertNodepoolRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertNodepoolRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNodepool()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertNodepoolRequestValidationError{
					field:  "Nodepool",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertNodepoolRequestValidationError{
					field:  "Nodepool",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNodepool()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertNodepoolRequestValidationError{
				field:  "Nodepool",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertNodepoolRequestMultiError(errors)
	}

	return nil
}

// UpsertNodepoolRequestMultiError is an error wrapping multiple validation
// errors returned by UpsertNodepoolRequest.ValidateAll() if the designated
// constraints aren't met.
type UpsertNodepoolRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertNodepoolRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertNodepoolRequestMultiError) AllErrors() []error { return m }

// UpsertNodepoolRequestValidationError is the validation error returned by
// UpsertNodepoolRequest.Validate if the designated constraints aren't met.
type UpsertNodepoolRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertNodepoolRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertNodepoolRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertNodepoolRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertNodepoolRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertNodepoolRequestValidationError) ErrorName() string {
	return "UpsertNodepoolRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertNodepoolRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertNodepoolRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertNodepoolRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertNodepoolRequestValidationError{}

// Validate checks the field values on UpsertNodepoolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertNodepoolResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertNodepoolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertNodepoolResponseMultiError, or nil if none found.
func (m *UpsertNodepoolResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertNodepoolResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpsertNodepoolResponseMultiError(errors)
	}

	return nil
}

// UpsertNodepoolResponseMultiError is an error wrapping multiple validation
// errors returned by UpsertNodepoolResponse.ValidateAll() if the designated
// constraints aren't met.
type UpsertNodepoolResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertNodepoolResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertNodepoolResponseMultiError) AllErrors() []error { return m }

// UpsertNodepoolResponseValidationError is the validation error returned by
// UpsertNodepoolResponse.Validate if the designated constraints aren't met.
type UpsertNodepoolResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertNodepoolResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertNodepoolResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertNodepoolResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertNodepoolResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertNodepoolResponseValidationError) ErrorName() string {
	return "UpsertNodepoolResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertNodepoolResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertNodepoolResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertNodepoolResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertNodepoolResponseValidationError{}

// Validate checks the field values on GetNodepoolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetNodepoolRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNodepoolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNodepoolRequestMultiError, or nil if none found.
func (m *GetNodepoolRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNodepoolRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetNodepoolRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetNodepoolRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetNodepoolRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetNodepoolRequestMultiError(errors)
	}

	return nil
}

// GetNodepoolRequestMultiError is an error wrapping multiple validation errors
// returned by GetNodepoolRequest.ValidateAll() if the designated constraints
// aren't met.
type GetNodepoolRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNodepoolRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNodepoolRequestMultiError) AllErrors() []error { return m }

// GetNodepoolRequestValidationError is the validation error returned by
// GetNodepoolRequest.Validate if the designated constraints aren't met.
type GetNodepoolRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNodepoolRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNodepoolRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNodepoolRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNodepoolRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNodepoolRequestValidationError) ErrorName() string {
	return "GetNodepoolRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetNodepoolRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNodepoolRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNodepoolRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNodepoolRequestValidationError{}

// Validate checks the field values on GetNodepoolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetNodepoolResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNodepoolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNodepoolResponseMultiError, or nil if none found.
func (m *GetNodepoolResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNodepoolResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNodepool()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetNodepoolResponseValidationError{
					field:  "Nodepool",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetNodepoolResponseValidationError{
					field:  "Nodepool",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNodepool()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetNodepoolResponseValidationError{
				field:  "Nodepool",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetNodepoolResponseMultiError(errors)
	}

	return nil
}

// GetNodepoolResponseMultiError is an error wrapping multiple validation
// errors returned by GetNodepoolResponse.ValidateAll() if the designated
// constraints aren't met.
type GetNodepoolResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNodepoolResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNodepoolResponseMultiError) AllErrors() []error { return m }

// GetNodepoolResponseValidationError is the validation error returned by
// GetNodepoolResponse.Validate if the designated constraints aren't met.
type GetNodepoolResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNodepoolResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNodepoolResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNodepoolResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNodepoolResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNodepoolResponseValidationError) ErrorName() string {
	return "GetNodepoolResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetNodepoolResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNodepoolResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNodepoolResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNodepoolResponseValidationError{}

// Validate checks the field values on ListNodepoolsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListNodepoolsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListNodepoolsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListNodepoolsRequestMultiError, or nil if none found.
func (m *ListNodepoolsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListNodepoolsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Organization

	if all {
		switch v := interface{}(m.GetRequest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListNodepoolsRequestValidationError{
					field:  "Request",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListNodepoolsRequestValidationError{
					field:  "Request",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRequest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListNodepoolsRequestValidationError{
				field:  "Request",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListNodepoolsRequestMultiError(errors)
	}

	return nil
}

// ListNodepoolsRequestMultiError is an error wrapping multiple validation
// errors returned by ListNodepoolsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListNodepoolsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListNodepoolsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListNodepoolsRequestMultiError) AllErrors() []error { return m }

// ListNodepoolsRequestValidationError is the validation error returned by
// ListNodepoolsRequest.Validate if the designated constraints aren't met.
type ListNodepoolsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListNodepoolsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListNodepoolsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListNodepoolsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListNodepoolsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListNodepoolsRequestValidationError) ErrorName() string {
	return "ListNodepoolsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListNodepoolsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListNodepoolsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListNodepoolsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListNodepoolsRequestValidationError{}

// Validate checks the field values on ListNodepoolsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListNodepoolsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListNodepoolsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListNodepoolsResponseMultiError, or nil if none found.
func (m *ListNodepoolsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListNodepoolsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetNodepools() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListNodepoolsResponseValidationError{
						field:  fmt.Sprintf("Nodepools[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListNodepoolsResponseValidationError{
						field:  fmt.Sprintf("Nodepools[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListNodepoolsResponseValidationError{
					field:  fmt.Sprintf("Nodepools[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Token

	if len(errors) > 0 {
		return ListNodepoolsResponseMultiError(errors)
	}

	return nil
}

// ListNodepoolsResponseMultiError is an error wrapping multiple validation
// errors returned by ListNodepoolsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListNodepoolsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListNodepoolsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListNodepoolsResponseMultiError) AllErrors() []error { return m }

// ListNodepoolsResponseValidationError is the validation error returned by
// ListNodepoolsResponse.Validate if the designated constraints aren't met.
type ListNodepoolsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListNodepoolsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListNodepoolsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListNodepoolsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListNodepoolsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListNodepoolsResponseValidationError) ErrorName() string {
	return "ListNodepoolsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListNodepoolsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListNodepoolsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListNodepoolsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListNodepoolsResponseValidationError{}

// Validate checks the field values on DeleteNodepoolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteNodepoolRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteNodepoolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteNodepoolRequestMultiError, or nil if none found.
func (m *DeleteNodepoolRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteNodepoolRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteNodepoolRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteNodepoolRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteNodepoolRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteNodepoolRequestMultiError(errors)
	}

	return nil
}

// DeleteNodepoolRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteNodepoolRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteNodepoolRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteNodepoolRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteNodepoolRequestMultiError) AllErrors() []error { return m }

// DeleteNodepoolRequestValidationError is the validation error returned by
// DeleteNodepoolRequest.Validate if the designated constraints aren't met.
type DeleteNodepoolRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteNodepoolRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteNodepoolRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteNodepoolRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteNodepoolRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteNodepoolRequestValidationError) ErrorName() string {
	return "DeleteNodepoolRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteNodepoolRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteNodepoolRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteNodepoolRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteNodepoolRequestValidationError{}

// Validate checks the field values on DeleteNodepoolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteNodepoolResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteNodepoolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteNodepoolResponseMultiError, or nil if none found.
func (m *DeleteNodepoolResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteNodepoolResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteNodepoolResponseMultiError(errors)
	}

	return nil
}

// DeleteNodepoolResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteNodepoolResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteNodepoolResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteNodepoolResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteNodepoolResponseMultiError) AllErrors() []error { return m }

// DeleteNodepoolResponseValidationError is the validation error returned by
// DeleteNodepoolResponse.Validate if the designated constraints aren't met.
type DeleteNodepoolResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteNodepoolResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteNodepoolResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteNodepoolResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteNodepoolResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteNodepoolResponseValidationError) ErrorName() string {
	return "DeleteNodepoolResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteNodepoolResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteNodepoolResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteNodepoolResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteNodepoolResponseValidationError{}
