// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: authorizer/definition.proto

package authorizer

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "github.com/unionai/terraform-provider-unionai/proto/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.Deployment(0)
)

// Validate checks the field values on RoleAssignment with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleAssignment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleAssignment with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleAssignmentMultiError,
// or nil if none found.
func (m *RoleAssignment) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleAssignment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRoleId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RoleAssignmentValidationError{
					field:  "RoleId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RoleAssignmentValidationError{
					field:  "RoleId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRoleId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RoleAssignmentValidationError{
				field:  "RoleId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetIdentities() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RoleAssignmentValidationError{
						field:  fmt.Sprintf("Identities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RoleAssignmentValidationError{
						field:  fmt.Sprintf("Identities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RoleAssignmentValidationError{
					field:  fmt.Sprintf("Identities[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RoleAssignmentMultiError(errors)
	}

	return nil
}

// RoleAssignmentMultiError is an error wrapping multiple validation errors
// returned by RoleAssignment.ValidateAll() if the designated constraints
// aren't met.
type RoleAssignmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleAssignmentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleAssignmentMultiError) AllErrors() []error { return m }

// RoleAssignmentValidationError is the validation error returned by
// RoleAssignment.Validate if the designated constraints aren't met.
type RoleAssignmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleAssignmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleAssignmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleAssignmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleAssignmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleAssignmentValidationError) ErrorName() string { return "RoleAssignmentValidationError" }

// Error satisfies the builtin error interface
func (e RoleAssignmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleAssignment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleAssignmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleAssignmentValidationError{}

// Validate checks the field values on PolicyAssignment with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PolicyAssignment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PolicyAssignment with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PolicyAssignmentMultiError, or nil if none found.
func (m *PolicyAssignment) ValidateAll() error {
	return m.validate(true)
}

func (m *PolicyAssignment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPolicyId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PolicyAssignmentValidationError{
					field:  "PolicyId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PolicyAssignmentValidationError{
					field:  "PolicyId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolicyId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PolicyAssignmentValidationError{
				field:  "PolicyId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetIdentities() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PolicyAssignmentValidationError{
						field:  fmt.Sprintf("Identities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PolicyAssignmentValidationError{
						field:  fmt.Sprintf("Identities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PolicyAssignmentValidationError{
					field:  fmt.Sprintf("Identities[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PolicyAssignmentMultiError(errors)
	}

	return nil
}

// PolicyAssignmentMultiError is an error wrapping multiple validation errors
// returned by PolicyAssignment.ValidateAll() if the designated constraints
// aren't met.
type PolicyAssignmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PolicyAssignmentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PolicyAssignmentMultiError) AllErrors() []error { return m }

// PolicyAssignmentValidationError is the validation error returned by
// PolicyAssignment.Validate if the designated constraints aren't met.
type PolicyAssignmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PolicyAssignmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PolicyAssignmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PolicyAssignmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PolicyAssignmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PolicyAssignmentValidationError) ErrorName() string { return "PolicyAssignmentValidationError" }

// Error satisfies the builtin error interface
func (e PolicyAssignmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPolicyAssignment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PolicyAssignmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PolicyAssignmentValidationError{}

// Validate checks the field values on IdentityAssignment with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IdentityAssignment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdentityAssignment with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IdentityAssignmentMultiError, or nil if none found.
func (m *IdentityAssignment) ValidateAll() error {
	return m.validate(true)
}

func (m *IdentityAssignment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIdentity()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IdentityAssignmentValidationError{
					field:  "Identity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IdentityAssignmentValidationError{
					field:  "Identity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIdentity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IdentityAssignmentValidationError{
				field:  "Identity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetRoles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IdentityAssignmentValidationError{
						field:  fmt.Sprintf("Roles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IdentityAssignmentValidationError{
						field:  fmt.Sprintf("Roles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IdentityAssignmentValidationError{
					field:  fmt.Sprintf("Roles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetPolicies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IdentityAssignmentValidationError{
						field:  fmt.Sprintf("Policies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IdentityAssignmentValidationError{
						field:  fmt.Sprintf("Policies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IdentityAssignmentValidationError{
					field:  fmt.Sprintf("Policies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return IdentityAssignmentMultiError(errors)
	}

	return nil
}

// IdentityAssignmentMultiError is an error wrapping multiple validation errors
// returned by IdentityAssignment.ValidateAll() if the designated constraints
// aren't met.
type IdentityAssignmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdentityAssignmentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdentityAssignmentMultiError) AllErrors() []error { return m }

// IdentityAssignmentValidationError is the validation error returned by
// IdentityAssignment.Validate if the designated constraints aren't met.
type IdentityAssignmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdentityAssignmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdentityAssignmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdentityAssignmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdentityAssignmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdentityAssignmentValidationError) ErrorName() string {
	return "IdentityAssignmentValidationError"
}

// Error satisfies the builtin error interface
func (e IdentityAssignmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdentityAssignment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdentityAssignmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdentityAssignmentValidationError{}

// Validate checks the field values on OrganizationOptions with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrganizationOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrganizationOptions with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrganizationOptionsMultiError, or nil if none found.
func (m *OrganizationOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *OrganizationOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AuthorizationType

	// no validation rules for Parent

	// no validation rules for Deployment

	if len(errors) > 0 {
		return OrganizationOptionsMultiError(errors)
	}

	return nil
}

// OrganizationOptionsMultiError is an error wrapping multiple validation
// errors returned by OrganizationOptions.ValidateAll() if the designated
// constraints aren't met.
type OrganizationOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationOptionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationOptionsMultiError) AllErrors() []error { return m }

// OrganizationOptionsValidationError is the validation error returned by
// OrganizationOptions.Validate if the designated constraints aren't met.
type OrganizationOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationOptionsValidationError) ErrorName() string {
	return "OrganizationOptionsValidationError"
}

// Error satisfies the builtin error interface
func (e OrganizationOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizationOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationOptionsValidationError{}
